todo/urls.py
from django.urls import path
from .views import (
    IndexView,
    ToggleTaskStatus,
    TaskListView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagDetailView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path(
        "toggle-task-status/<int:pk>/",
        ToggleTaskStatus.as_view(),
        name="toggle-task-status"
    ),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/<int:pk>/detail/", TaskDetailView.as_view(), name="task-detail"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path(
        "tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"
    ),
    path(
        "tags/<int:pk>/detail/", TagDetailView.as_view(), name="tag-detail"
    ),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    def __str__(self):
        return self.content[:50]

todo/forms.py
from django import forms
from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"})
        }

todo/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic, View
from .models import Task, Tag
from .forms import TaskForm


class IndexView(generic.ListView):
    """View function for the home page of the site."""
    model = Task
    template_name = "todo/index.html"
    context_object_name = "tasks"
    ordering = ["is_done", "-created_at"]
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by(*self.ordering)


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    queryset = Task.objects.order_by("is_done", "-created_at")
    paginate_by = 5


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskDetailView(generic.DetailView):
    model = Task


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    queryset = Tag.objects.order_by("name")
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TagDetailView(generic.DetailView):
    model = Tag


class ToggleTaskStatus(View):
    def post(self, request, pk):
        task = Task.objects.get(id=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect(reverse_lazy("todo:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>

    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
<h1>
  TODO list
  <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
    Add task
  </a>
</h1>

{% if tasks %}
  <ul class="list-group list-group-flush">
  {% for task in tasks %}
    <li class="list-group-item">
      <p class="font-weight-bold">{{ task.content }} {% if task.is_done %}
          <span style="color: green;">
            Done
          </span>
        {% else %}
          <span style="color: red;">
            Not Done
          </span>
        {% endif %}</p>{% include "todo/toggle_task_status.html" %}
      <p>Created: {{ task.created_at|date:"F j, Y, g:i a" }}
      {% if task.deadline %}
        <span style="color: #b40505;">
          Deadline: {{ task.deadline|date:"F j, Y, g:i a" }}
        </span>
      {% endif %}</p>
      <p class="text-secondary">Tags:
      {% if task.tags.all %}
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}
      {% else %}
        No tags
      {% endif %}
    <a href="{% url 'todo:task-update' pk=task.id %}">
    Update
    </a>
    <a href="{% url 'todo:task-delete' pk=task.id %}">
    Delete
    </a></p>
    </li>
  {% endfor %}
  </ul>

{% else %}
  <p>There are no tasks</p>
{% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="section section-md">
    <div class="container">
      <div class="row mb-5 mb-lg-5">
        <div class="col-lg-4 col-sm-6">
          <h1>Delete {{ tag.name }}?</h1>
          <a class="btn btn-outline-success" href="{% url 'todo:tag-list' %}">
            Cancel
          </a>
          <form action="" method="post">
            {% csrf_token %}

            <input type="submit" value="Yes, delete" class="btn btn-outline-danger">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/todo/tag_detail.html
{% extends "base.html" %}
{% block content %}
  {{ tag.name }}
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
<h1>
  Tags
  <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
    Add
  </a>
</h1>
{% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-secondary">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="section section-md">
    <div class="container">
      <div class="row mb-5 mb-lg-5">
        <div class="col-lg-4 col-sm-6">
          <h1>Delete {{ task.content }}?</h1>
          <a class="btn btn-outline-success" href="{% url 'todo:task-list' %}">
            Cancel
          </a>
          <form action="" method="post">
            {% csrf_token %}

            <input type="submit" value="Yes, delete" class="btn btn-outline-danger">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/todo/task_detail.html
{% extends "base.html" %}
{% block content %}
  {{ task.name }}
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
<h1>
  TODO list
  <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
    Add task
  </a>
</h1>

{% if task_list %}
  <ul class="list-group list-group-flush">
  {% for task in task_list %}
    <li class="list-group-item">
      <p class="font-weight-bold">{{ task.content }} {% if task.is_done %}
          <span style="color: green;">
            Done
          </span>
        {% else %}
          <span style="color: red;">
            Not Done
          </span>
        {% endif %}</p>{% include "todo/toggle_task_status.html" %}
      <p>Created: {{ task.created_at|date:"F j, Y, g:i a" }}
      {% if task.deadline %}
        <span style="color: #b40505;">
          Deadline: {{ task.deadline|date:"F j, Y, g:i a" }}
        </span>
      {% endif %}</p>
      <p class="text-secondary">Tags:
      {% if task.tags.all %}
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}
      {% else %}
        No tags
      {% endif %}
    <a href="{% url 'todo:task-update' pk=task.id %}">
    Update
    </a>
    <a href="{% url 'todo:task-delete' pk=task.id %}">
    Delete
    </a></p>
    </li>
  {% endfor %}
  </ul>

{% else %}
  <p>There are no tasks</p>
{% endif %}
{% endblock %}

templates/todo/toggle_task_status.html
<form method="post" action="{% url 'todo:toggle-task-status' pk=task.pk %}">
  {% csrf_token %}
  {% if task.is_done %}
    <button type="submit" class="btn btn-secondary link-to-page">
      Undo
    </button>
  {% else %}
    <button type="submit" class="btn btn-success link-to-page">
      Completed
    </button>
  {% endif %}
</form>